### ISSUE TITLE
Identificar se as redes disponíveis na UFPB estão funcionando

### ISSUE THREAD

**Issue by ghost** [AbraaoHonorio/E-caiu#1]
*Edit*: apertei no botão *Submit new issue* cedo demais, rsrs

Projeto :top:, @AbraaoHonorio! :grinning:

Deixando brincadeiras de lado, eu gostaria de saber se seria interessante colocar no seu serviço a a possibilidade de verificar a disponibilidade das redes da UFPB. Não sei se há um modo de fazer isso automaticamente sem, antes, fazer um *survey* das redes dentro da UFPB e, após isso, colocar um serviço em dispositivos conectados a essas redes que verifica se a conexão está *ok* e envia os dados para o servidor. Porém, se houver um front-end mais tarde, usuários poderão colocar os dados manualmente no serviço.

Acho que meu pedido cai um pouco fora da ideia do projeto, mas não custa perguntar :)  
Diga-me se acha essa proposta viável para o projeto; posso trabalhar junto na implementação.

Edit: essa proposta parece inviável, devido a restrições como acesso aos roteadores e a questão de IPs dinâmicos.

**Comment by AbraaoHonorio** [comment]
@nuskorpios primeiramente fico feliz com a sua participação. Falando sobre a sua sugestão, a mesma sai um pouco fora do eixo do projeto de imediato mas eu achei super interessante e extremamente válida para deixar o projeto ainda mais completo, logo, podendo sim ser agregada ao projeto. 
Se quiser começar a implementação fique à vontade, recomendo fazer um texto curto explicando sobre o a mesma e dividir em funcionalidades e colocá-las no [README](https://github.com/AbraaoHonorio/E-caiu/blob/master/README.md). De antemão tenho que finalizar a API(conexão com BD e deploy) para que os usúarios possam o mais rápidamente acessar as informações, mas assim que finalizar isso eu posso pegar alguma feature escrita por ti e começar a implementar.
